tof_true = ["That's so true.",
            "REALL",
            "I haven't seen something more real than this",
            "Real 100%",
            "True queen.",
            "Yeah, very real.",
            "Dawh you kidding? That's real",
            "Straight up facts.",
            "Spitting facts.",
            "Valid.",
            "True king.",
            "So real.",
            "frfr.",
            "Yuh uh."]

tof_false = ["That's so false.",
            "FAKE",
            "I haven't seen something more fake than this",
            "False 100%",
            "False queen",
            "Yeah, very false.",
            "Dawh you kidding? That's false",
             "Nah",
             "LIES.",
             "False king.",
             "Nuh uh.",
             "That's so fake.",
             "Not frfr.",
             "Don't try again <3"]